In [1]:
import numpy as np

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [3]:
W = np.linalg.inv(X @ X.T) @ X @ y
W

array([47.23214286,  3.91071429])

In [6]:
def calc_mse(y, y_pred):
  return np.mean((y - y_pred)**2)

In [25]:
n = X.shape[1]
alpha = 1e-4
min_dist = 1e-7
max_iter = 1e+5
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.0001)

1. Количество операций определим через условие изменения весов меньше заданного min_dist

In [7]:
delta = np.inf
iter_ = 0
while (np.abs(delta) > min_dist) and (iter_ < max_iter):
    iter_ += 1
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    for i in range(W.shape[0]):
        delta = alpha * (1/n * 2 * np.sum(X[i] * (y_pred - y)))
        W[i] -= delta
    if iter_ % 10000 == 0:
        print(iter_, W, delta)
W

10000 [31.64269117  6.78942579] 0.00029935385526700547
20000 [41.72106496  4.92837698] 0.00010582555741904798
30000 [45.28390374  4.27047154] 3.741073784722517e-05
40000 [46.5434145   4.03789325] 1.3225191913988966e-05
50000 [46.98866825  3.95567373] 4.675280714234305e-06
60000 [47.14607135  3.92660805] 1.6527737290643078e-06
70000 [47.20171544  3.91633294] 5.84277429821043e-07
80000 [47.22138636  3.91270055] 2.0654981925858353e-07


array([47.22693525,  3.91167591])

2. Заменим цикл по весам матричной операцией 

In [26]:
delta_mean = 1
iter_ = 0
while (np.abs(delta_mean) > min_dist) and (iter_ < max_iter):
    iter_ += 1
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    delta= alpha * (1/n * 2 * (X @ (y_pred - y)))    
    delta_mean = delta.mean()
    W = W - delta
    if iter_ % 10000 == 0:
        print(iter_, W, delta_mean)
W

10000 [31.64269117  6.78942579] -0.0006608875296698905
20000 [41.72106496  4.92837698] -0.00023363250543557542
30000 [45.28390374  4.27047154] -8.259218875487833e-05
40000 [46.5434145   4.03789325] -2.919743393842197e-05
50000 [46.98866825  3.95567373] -1.0321680069747575e-05
60000 [47.14607135  3.92660805] -3.6488507752525126e-06
70000 [47.20171544  3.91633294] -1.2899171346210639e-06
80000 [47.22138636  3.91270055] -4.560028120296523e-07
90000 [47.22834029  3.91141646] -1.6120304086967965e-07


array([47.22978423,  3.91114982])