In [1]:
import numpy as np

In [29]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [3]:
W = np.linalg.inv(X @ X.T) @ X @ y
W

array([47.23214286,  3.91071429])

In [6]:
def calc_mse(y, y_pred):
  return np.mean((y - y_pred)**2)

In [32]:
n = X.shape[1]
alpha = 1e-4
min_dist = 1e-7
max_iter = 1e+6
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.0001)

1. Количество операций определим через условие изменения весов меньше заданного min_dist

In [7]:
delta = np.inf
iter_ = 0
while (np.abs(delta) > min_dist) and (iter_ < max_iter):
    iter_ += 1
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    for i in range(W.shape[0]):
        delta = alpha * (1/n * 2 * np.sum(X[i] * (y_pred - y)))
        W[i] -= delta
    if iter_ % 10000 == 0:
        print(iter_, W, delta)
W

10000 [31.64269117  6.78942579] 0.00029935385526700547
20000 [41.72106496  4.92837698] 0.00010582555741904798
30000 [45.28390374  4.27047154] 3.741073784722517e-05
40000 [46.5434145   4.03789325] 1.3225191913988966e-05
50000 [46.98866825  3.95567373] 4.675280714234305e-06
60000 [47.14607135  3.92660805] 1.6527737290643078e-06
70000 [47.20171544  3.91633294] 5.84277429821043e-07
80000 [47.22138636  3.91270055] 2.0654981925858353e-07


array([47.22693525,  3.91167591])

2. Заменим цикл по весам матричной операцией 

In [33]:
delta_mean = np.inf
iter_ = 0
while (np.abs(delta_mean) > min_dist) and (iter_ < max_iter):
    iter_ += 1
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    delta= alpha * (1/n * 2 * (X @ (y_pred - y)))    
    delta_mean = np.linalg.norm(delta, ord=2)
    W = W - delta
    if iter_ % 10000 == 0:
        print(iter_, W, delta_mean)
W

10000 [31.64269117  6.78942579] 0.001648536226000933
20000 [41.72106496  4.92837698] 0.0005827794163028026
30000 [45.28390374  4.27047154] 0.00020602025160838577
40000 [46.5434145   4.03789325] 7.283089087471278e-05
50000 [46.98866825  3.95567373] 2.574668569810548e-05
60000 [47.14607135  3.92660805] 9.101794808150032e-06
70000 [47.20171544  3.91633294] 3.2176051589880802e-06
80000 [47.22138636  3.91270055] 1.1374660907525248e-06
90000 [47.22834029  3.91141646] 4.0210934643143555e-07
100000 [47.2307986   3.91096251] 1.4215098615316324e-07


array([47.23119726,  3.9108889 ])